### ISSUE TITLE
Not loading library

### ISSUE THREAD

**Issue by tytower** [damellis/attiny#66] opened 2015-05-28 07:51 UTC
Hi david Thanks for your contributions over the years . Helped me a lot 
I am getting an error loading arduino 1.6.4 and it will not now open at all.

 ./arduino
Picked up JAVA_TOOL_OPTIONS: 
Loading configuration...
Initializing packages...
java.lang.NullPointerException
	at cc.arduino.contributions.packages.ContributedToolReference.resolve(ContributedToolReference.java:43)
	at cc.arduino.contributions.packages.ContributedPlatform.resolveToolsDependencies(ContributedPlatform.java:76)
	at cc.arduino.contributions.packages.ContributionsIndexer.parseIndex(ContributionsIndexer.java:92)
	at processing.app.BaseNoGui.initPackages(BaseNoGui.java:615)
	at processing.app.Base.<init>(Base.java:306)
	at processing.app.Base.guardedMain(Base.java:222)
	at processing.app.Base.main(Base.java:133)
#

**Comment by per1234** [comment] 2015-05-28 08:00
Looks like maybe a similar issue to the one reported here: http://forum.arduino.cc/index.php?topic=324095.0
- Did you use Boards Manager to install attiny?
- Do you have any other Boards Manager URLs entered in ***File > Preferences > Additional Boards Manager URLs:***?
- Are you saying that your IDE will no longer load(only the splash screen shows)?

**Comment by tytower** [comment] 2015-05-28 08:50
The IDE no longer starts . There is no splash screen .The error is found by running the start script in a terminal.

I have ESP8266/Arduino in the boards manager also and it was loading without problem before I added attiny. 
---------------------------------------------------------------------On Thu, 28 May 2015 01:00:04 -0700
per1234 <notifications@github.com> wrote:

> Looks like maybe a similar issue to the one reported here: http://forum.arduino.cc/index.php?topic=324095.0
> - Did you use Boards Manager to install attiny?
> - Do you have any other Boards Manager URLs entered in ***File > Preferences > Additional Boards Manager URLs:***?
> - Are you saying that your IDE will no longer load(only the splash screen shows)?
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/damellis/attiny/issues/66#issuecomment-106223017


-- 
Yahoo <tytower@yahoo.com>

**Comment by per1234** [comment] 2015-05-28 09:14
That's the same combination that's causing anath3ma on the forum a problem. Are you using the ESP8266 URL:
http://arduino.esp8266.com/package_esp8266com_index.json ?

You should be able to get the IDE working by deleting the file Arduino15/package_esp8266com_index.json
Let me know if you can't find it and I'll help locate it.

I think the problem is with the ESP8266 file and not attiny because I had the same problem when I tried with ESP8266 and other URLs. I have successfully installed ESP8266 and attiny simultaneously using Adafruit's package index:
https://adafruit.github.io/arduino-board-index/package_adafruit_index.json
Which is based on the same project though it is esp8266 1.6.2 instead of 1.6.4 and esptool 0.4.2 instead of 0.4.4
So you could give that a try and I'll look at the other package index file and see if I can find the issue.

**Comment by tytower** [comment] 2015-05-28 10:19
No I went into /root/.arduino15 and deleted your json file for now as I am working on the ESP8266 module for now . Ill come back later for the tiny -thanks

**Comment by per1234** [comment] 2015-05-28 11:14
A workaround for having both is to do a manual installation of attiny and a Boards Manager installation of http://arduino.esp8266.com/package_esp8266com_index.json

**Comment by per1234** [comment] 2015-05-29 16:53
I have altered the attiny Boards Manager json index file to solve this issue. ESP8266 and attiny should now be able to be added simultaneously to your Additional Boards Manager URLs. Also, the problem with the Arduino IDE that was causing it not to load with the previous attiny json index file has been fixed and is available in the hourly build. Sorry for any inconvenience this has caused you.
Per

**Comment by tytower** [comment] 2015-05-29 19:55
Not a matter of inconvenience . Thank you for the library .Superb chip

---------------------------------------------------------------------------On Fri, 29 May 2015 09:53:28 -0700
per1234 <notifications@github.com> wrote:

> I have altered the attiny Boards Manager json index file to solve this issue. ESP8266 and attiny should now be able to be added simultaneously to your Additional Boards Manager URLs. Also, the problem with the Arduino IDE that was causing it not to load with the previous attiny json index file has been fixed and is available in the hourly build. Sorry for any inconvenience this has caused you.
> Per
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/damellis/attiny/issues/66#issuecomment-106869715


-- 
Yahoo <tytower@yahoo.com>

**Comment by damellis** [comment] 2016-03-07 19:14
Sounds like this was fixed, so I'm closing this.

**Closed by damellis** 2016-03-07 19:14 UTC
